feat: add babel-sugar-composition-api-inject-h
vuejs/jsx pull request #142
Opened 2020-07-07 16:25 UTC by antfu

Thanks to @luwanquan who made the jsx plugin https://github.com/luwanquan/babel-preset-vca-jsx which is the base of these changes.

#76, This PR provides minimal support for @vue/composition-api. It's able to inject the `h` function from @vue/composition-api. As for the `v-model` support, it's a bit tricky as the current implementation relies on internal utils like `this._u`. I would try to find out a good solution for it and will make another PR.

It is disabled by default. To use it, users need to set the config by:
```json
{
  "presets": [
    [
      "@vue/babel-preset-jsx",
      {
        "compositionAPI": true
      }
    ]
  ]
}
```

2020-08-11 13:39 UTC, Amour1688 commented on packages/babel-sugar-composition-api-render-instance/src/index.js
> +              JSXAttribute(path) {
`path` is already declared in the upper scope.

2020-08-12 07:59 UTC, haoqunjiang requested changes

2020-08-12 07:59 UTC, haoqunjiang commented on packages/babel-sugar-composition-api-inject-h/README.md
> +This plugin automatically injects `h` in every method that has JSX. By using this plugin you don't have to always specifically declare `h` as first parameter in your `render()` function.
> By using this plugin you don't have to always specifically declare `h` as first parameter in your `render()` function.

This statement doesn't apply to composition-api usage. Need rewording.

2020-08-12 07:59 UTC, haoqunjiang commented on packages/babel-sugar-composition-api-render-instance/README.md
> +}
Wrong description

2020-08-12 07:59 UTC, haoqunjiang commented on packages/babel-sugar-composition-api-render-instance/README.md
> +Babel syntactic sugar for replaceing `this` with `getCurrentInstance()` in Vue JSX with @vue/composition-api
```suggestion
Babel syntactic sugar for replacing `this` with `getCurrentInstance()` in Vue JSX with @vue/composition-api
```

2020-08-12 08:25 UTC, haoqunjiang requested changes

2020-08-12 08:25 UTC, sodatea commented on packages/babel-sugar-composition-api-inject-h/test/test.js
> +      const h = this.$createElement;
Duplicate declaration of `h`. This is not valid JS.

2020-09-21 21:49 UTC, antfu commented
Sorry for the delay. Updated.

2020-09-22 05:32 UTC, sodatea commented
The example in the README of `render-instance` is still wrong.

2020-10-14 05:51 UTC, nour-dev commented
is this pull request need any changes to be merged ? @antfu @sodatea

2020-10-16 02:19 UTC, antfu commented
> The example in the README of `render-instance` is still wrong.

Updated.

2020-10-16 10:25 UTC, sodatea approved these changes

2020-10-16 10:25 UTC, sodatea commented
Thanks!

2020-10-16 10:25 UTC, merged

2020-10-16 13:18 UTC, sodatea commented
Released as v1.2.1

https://github.com/vuejs/jsx/releases/tag/v1.2.1

2020-10-16 14:13 UTC, jvbianchi commented
With this PR I'm getting this error:

```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property '$set' of undefined"

TypeError: Cannot read property '$set' of undefined
```

2020-10-16 14:18 UTC, sodatea commented
Any reproductions?
It's expected to break some code if the project hasn't turned on the `@vue/composition-api` plugin. That's the reason why the flag is off by default.

2020-10-16 14:32 UTC, jvbianchi commented
Reproduction: https://github.com/jvbianchi/error-jsx

2020-10-16 14:49 UTC, sodatea commented
Got it. The `render-instance` plugin has only tested for custom component v-model, forgetting `<input vModel>`

2020-10-16 14:52 UTC, jvbianchi commented
Great. Can I delete the test repo?

2020-10-16 14:55 UTC, sodatea commented
Yeah. Feel free to. Thanks for the report!

2020-10-21 10:00 UTC, sodatea commented
@antfu The issue here is that in the `render-instance` plugin, we can't simply replace `this` with `getCurrentInstance()` in a callback, because when the callback is invoked, there may not be an actual "currentInstance".

Here we need an approach that works like the classic `arrow-functions` transformation:

---

With `arrow-functions` transformation:
```js
export default {
  render() {
    return h("div", [h("input", {
      "on": {
        "input": ($event) => {
          if ($event.target.composing) return;
          this.$set(a, "value", $event.target.value);
        }
      },
    })
  }
}
```

turns into

```js
export default {
  render() {
    var _this = this
    return h("div", [h("input", {
      "on": {
        "input": function input($event) {
          if ($event.target.composing) return;
          _this.$set(a, "value", $event.target.value);
        }
      },
    })
  }
}
```

Similarly, with `render-instance` transformation, the code should be transformed into
```js
export default {
  render() {
    var _this = getCurrentInstance()
    return h("div", [h("input", {
      "on": {
        "input": function input($event) {
          if ($event.target.composing) return;
          _this.$set(a, "value", $event.target.value);
        }
      },
    })
  }
}
```