Arrow function support for h injection
vuejs/jsx pull request #90
Opened 2019-12-15 13:48 UTC by dword-design

The current implementation of babel-sugar-inject-h does not support arrow functions. However, it is possible to add arrow function support with just some small adjustments. Here you go.

2019-12-16 14:36 UTC, DM2489 commented
@dword-design, if I'm reading this correctly, this should fix my issue? https://github.com/vuejs/jsx/issues/91

2019-12-16 15:56 UTC, dword-design commented
@DM2489 yeah looks like it

2020-02-26 10:05 UTC, haoqunjiang requested changes
This PR assumes that any function that contains JSX code should accept an `h` as its first parameter, which isn't true in real-world use cases.

2020-03-02 19:34 UTC, dword-design commented
@sodatea Yeah you're right. I actually couldn't find a use case where this is not the case. Do you have one?
In general, this PR is supposed to mainly support arrow functions without a this parameter because if a project is into functional programming, it wants to add a linting rule to enforce arrow function usage. So as long this is fulfilled, I'd be fine :).

2020-06-26 18:03 UTC, dword-design commented
Closing in favor of https://github.com/vuejs/jsx/pull/9/files

2020-06-26 18:03 UTC, closed without merging